// <auto-generated />
namespace PMQLSQA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_column_NhanVien_MaNhanVien : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_column_NhanVien_MaNhanVien));
        
        string IMigrationMetadata.Id
        {
            get { return "202111040840263_add_column_NhanVien_MaNhanVien"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
